-- =====================================================
-- MES Production Confirmation - Demo Schema (H2 Compatible)
-- For screenshots and documentation purposes
-- =====================================================

-- 1. Database Patches Table (for patch service compatibility)
CREATE TABLE IF NOT EXISTS database_patches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patch_number INTEGER NOT NULL UNIQUE,
    patch_name VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    applied_on TIMESTAMP NOT NULL,
    applied_by VARCHAR(100),
    execution_time_ms BIGINT,
    checksum VARCHAR(64),
    success BOOLEAN NOT NULL,
    error_message TEXT
);

-- 2. Users Table
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    employee_id VARCHAR(50),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 3. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(100),
    customer_name VARCHAR(255),
    order_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'CREATED',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 4. Order Line Items Table
CREATE TABLE IF NOT EXISTS order_line_items (
    order_line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id),
    product_sku VARCHAR(100) NOT NULL,
    product_name VARCHAR(255),
    quantity DECIMAL(15,4) NOT NULL,
    unit VARCHAR(20) NOT NULL DEFAULT 'T',
    delivery_date DATE,
    status VARCHAR(30) NOT NULL DEFAULT 'CREATED',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 5. Bill of Material Table
CREATE TABLE IF NOT EXISTS bill_of_material (
    bom_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_sku VARCHAR(100) NOT NULL,
    bom_version VARCHAR(20) DEFAULT 'V1',
    material_id VARCHAR(100) NOT NULL,
    material_name VARCHAR(255),
    quantity_required DECIMAL(15,4) NOT NULL,
    unit VARCHAR(20) NOT NULL DEFAULT 'T',
    yield_loss_ratio DECIMAL(10,4) DEFAULT 1.0,
    sequence_level INTEGER NOT NULL DEFAULT 1,
    parent_bom_id BIGINT REFERENCES bill_of_material(bom_id),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 6. Processes Table
CREATE TABLE IF NOT EXISTS processes (
    process_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_line_id BIGINT NOT NULL REFERENCES order_line_items(order_line_id),
    bom_id BIGINT REFERENCES bill_of_material(bom_id),
    stage_name VARCHAR(100) NOT NULL,
    stage_sequence INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(30) NOT NULL DEFAULT 'READY',
    usage_decision VARCHAR(20),
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 7. Routing Table
CREATE TABLE IF NOT EXISTS routing (
    routing_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_id BIGINT NOT NULL REFERENCES processes(process_id),
    routing_name VARCHAR(100) NOT NULL,
    routing_type VARCHAR(20) NOT NULL DEFAULT 'SEQUENTIAL',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 8. Routing Steps Table
CREATE TABLE IF NOT EXISTS routing_steps (
    routing_step_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routing_id BIGINT NOT NULL REFERENCES routing(routing_id),
    operation_id BIGINT,
    sequence_number INTEGER NOT NULL,
    is_parallel BOOLEAN DEFAULT FALSE,
    mandatory_flag BOOLEAN DEFAULT TRUE,
    status VARCHAR(20) NOT NULL DEFAULT 'READY',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 9. Operations Table
CREATE TABLE IF NOT EXISTS operations (
    operation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_id BIGINT NOT NULL REFERENCES processes(process_id),
    routing_step_id BIGINT REFERENCES routing_steps(routing_step_id),
    operation_name VARCHAR(100) NOT NULL,
    operation_code VARCHAR(50),
    operation_type VARCHAR(50),
    sequence_number INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    target_qty DECIMAL(15,4),
    confirmed_qty DECIMAL(15,4),
    block_reason VARCHAR(500),
    blocked_by VARCHAR(100),
    blocked_on TIMESTAMP,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 10. Equipment Table
CREATE TABLE IF NOT EXISTS equipment (
    equipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    equipment_type VARCHAR(30) NOT NULL DEFAULT 'BATCH',
    capacity DECIMAL(15,4),
    capacity_unit VARCHAR(20),
    location VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 11. Operators Table
CREATE TABLE IF NOT EXISTS operators (
    operator_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    department VARCHAR(100),
    shift VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 12. Operation Equipment Usage Table
CREATE TABLE IF NOT EXISTS operation_equipment_usage (
    usage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL REFERENCES operations(operation_id),
    equipment_id BIGINT NOT NULL REFERENCES equipment(equipment_id),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    operator_id BIGINT REFERENCES operators(operator_id),
    status VARCHAR(20) NOT NULL DEFAULT 'LOGGED',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100)
);

-- 13. Production Confirmation Table (use CLOB instead of JSONB for H2)
CREATE TABLE IF NOT EXISTS production_confirmation (
    confirmation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL REFERENCES operations(operation_id),
    produced_qty DECIMAL(15,4) NOT NULL,
    scrap_qty DECIMAL(15,4) DEFAULT 0,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    delay_minutes INTEGER DEFAULT 0,
    delay_reason VARCHAR(100),
    process_parameters CLOB,
    rm_consumed CLOB,
    notes TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'CONFIRMED',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 14. Batches Table
CREATE TABLE IF NOT EXISTS batches (
    batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_number VARCHAR(100) NOT NULL UNIQUE,
    material_id VARCHAR(100) NOT NULL,
    material_name VARCHAR(255),
    quantity DECIMAL(15,4) NOT NULL,
    unit VARCHAR(20) NOT NULL DEFAULT 'T',
    generated_at_operation_id BIGINT REFERENCES operations(operation_id),
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    approved_by VARCHAR(100),
    approved_on TIMESTAMP,
    rejection_reason VARCHAR(500),
    rejected_by VARCHAR(100),
    rejected_on TIMESTAMP,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 15. Inventory Table
CREATE TABLE IF NOT EXISTS inventory (
    inventory_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id VARCHAR(100) NOT NULL,
    material_name VARCHAR(255),
    inventory_type VARCHAR(20) NOT NULL,
    state VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    quantity DECIMAL(15,4) NOT NULL,
    unit VARCHAR(20) NOT NULL DEFAULT 'T',
    batch_id BIGINT REFERENCES batches(batch_id),
    location VARCHAR(100),
    block_reason VARCHAR(500),
    blocked_by VARCHAR(100),
    blocked_on TIMESTAMP,
    scrap_reason VARCHAR(500),
    scrapped_by VARCHAR(100),
    scrapped_on TIMESTAMP,
    reserved_for_order_id BIGINT,
    reserved_for_operation_id BIGINT,
    reserved_by VARCHAR(100),
    reserved_on TIMESTAMP,
    reserved_qty DECIMAL(15,4),
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);

-- 16. Inventory Movement Table
CREATE TABLE IF NOT EXISTS inventory_movement (
    movement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT REFERENCES operations(operation_id),
    inventory_id BIGINT NOT NULL REFERENCES inventory(inventory_id),
    movement_type VARCHAR(20) NOT NULL,
    quantity DECIMAL(15,4) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'EXECUTED',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100)
);

-- 17. Batch Relations Table
CREATE TABLE IF NOT EXISTS batch_relations (
    relation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_batch_id BIGINT NOT NULL REFERENCES batches(batch_id),
    child_batch_id BIGINT NOT NULL REFERENCES batches(batch_id),
    operation_id BIGINT REFERENCES operations(operation_id),
    relation_type VARCHAR(20) NOT NULL DEFAULT 'MERGE',
    quantity_consumed DECIMAL(15,4) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100)
);

-- 18. Batch Order Allocation Table
CREATE TABLE IF NOT EXISTS batch_order_allocation (
    allocation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES batches(batch_id),
    order_line_id BIGINT NOT NULL REFERENCES order_line_items(order_line_id),
    allocated_qty DECIMAL(15,4) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'ALLOCATED',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100)
);

-- 19. Hold Records Table
CREATE TABLE IF NOT EXISTS hold_records (
    hold_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(30) NOT NULL,
    entity_id BIGINT NOT NULL,
    reason VARCHAR(100) NOT NULL,
    comments TEXT,
    applied_by VARCHAR(100) NOT NULL,
    applied_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_by VARCHAR(100),
    released_on TIMESTAMP,
    release_comments TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 20. Audit Trail Table
CREATE TABLE IF NOT EXISTS audit_trail (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    field_name VARCHAR(100),
    old_value TEXT,
    new_value TEXT,
    action VARCHAR(20) NOT NULL,
    changed_by VARCHAR(100) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 21. Delay Reasons (Lookup Table)
CREATE TABLE IF NOT EXISTS delay_reasons (
    reason_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason_code VARCHAR(50) NOT NULL UNIQUE,
    reason_description VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 22. Hold Reasons (Lookup Table)
CREATE TABLE IF NOT EXISTS hold_reasons (
    reason_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason_code VARCHAR(50) NOT NULL UNIQUE,
    reason_description VARCHAR(255) NOT NULL,
    applicable_to VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 23. Process Parameters Configuration Table
CREATE TABLE IF NOT EXISTS process_parameters_config (
    config_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type VARCHAR(50) NOT NULL,
    product_sku VARCHAR(100),
    parameter_name VARCHAR(100) NOT NULL,
    parameter_type VARCHAR(30) NOT NULL DEFAULT 'DECIMAL',
    unit VARCHAR(20),
    min_value DECIMAL(15,4),
    max_value DECIMAL(15,4),
    default_value DECIMAL(15,4),
    is_required BOOLEAN DEFAULT FALSE,
    display_order INTEGER DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 24. Confirmation Equipment Table
CREATE TABLE IF NOT EXISTS confirmation_equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    confirmation_id BIGINT NOT NULL REFERENCES production_confirmation(confirmation_id),
    equipment_id BIGINT NOT NULL REFERENCES equipment(equipment_id)
);

-- 25. Confirmation Operators Table
CREATE TABLE IF NOT EXISTS confirmation_operators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    confirmation_id BIGINT NOT NULL REFERENCES production_confirmation(confirmation_id),
    operator_id BIGINT NOT NULL REFERENCES operators(operator_id)
);

-- Create Indexes
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_order_lines_order_id ON order_line_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_lines_status ON order_line_items(status);
CREATE INDEX IF NOT EXISTS idx_processes_order_line ON processes(order_line_id);
CREATE INDEX IF NOT EXISTS idx_processes_status ON processes(status);
CREATE INDEX IF NOT EXISTS idx_operations_process ON operations(process_id);
CREATE INDEX IF NOT EXISTS idx_operations_status ON operations(status);
CREATE INDEX IF NOT EXISTS idx_inventory_state ON inventory(state);
CREATE INDEX IF NOT EXISTS idx_inventory_type ON inventory(inventory_type);
CREATE INDEX IF NOT EXISTS idx_inventory_batch ON inventory(batch_id);
CREATE INDEX IF NOT EXISTS idx_batches_status ON batches(status);
CREATE INDEX IF NOT EXISTS idx_batches_material ON batches(material_id);
CREATE INDEX IF NOT EXISTS idx_production_confirm_operation ON production_confirmation(operation_id);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_trail(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_hold_entity ON hold_records(entity_type, entity_id);
